### ISSUE TITLE
Removed policies folder

### ISSUE THREAD

**Issue by EHRETic** [Prowler2/Brave-Browser-GPO-Policy#3]
Hi there,

Superb work ! Thanks a lot ! 😀
I wanted to do it myself but why reinvent the wheel...

Not an issue with your template but I wanted to ask you what motivated the "Removed policies" folder.
Whas it because of incompatibility? 
(Might sound a stupid question, but as I didn't really use Brave for now, I don't know if they exist or not)

Because on my end, I want to create a CIS hardening GPO based on the Chrome one, but I saw that some of the settings were moved to this folder.

Let me know! Thanks again. 😉

**Comment by EHRETic** [comment]
Also, a small question: do you have any plan maintaining those?

**Comment by Prowler2** [comment]
@EHRETic, since Brave is based on Chrome source the easiest thing for me to do was modify the chrome source admx files for Brave use. I have no control over the "removed policies" or "deprecated polices" in the source files. I only modify what they release to fit Brave.
**Deprecated policies** - New releases of Chrome introduce new policies and sometimes deprecate old ones. Avoid using deprecated policies because they will be removed in future releases. 
**Removed policies** - Sometimes, policies are removed from Chrome because they're no longer useful. Avoid setting removed policies—they can cause Chrome Browser errors. 
[https://support.google.com/chrome/a/answer/7643500/deprecated-chrome-policies?hl=en](url)
